### ISSUE TITLE
Landing page has no color despite of style.css file

### ISSUE THREAD

**Issue by hackatme** [hackatme/gitOrgPracitce#1]
### **Pale landing page**
when you visit [the website](https://gitorgpractice.netlify.app/) . The _landing page_ seems to be vacant **no color in it**.

![image](https://github.com/hackatme/gitOrgPracitce/assets/86507189/18f065b1-8e97-403b-8bce-c9c3396478f6)

**Comment by Animesh59** [comment]
Hello, I want to work on this issue.

**Comment by Animesh59** [comment]
### Thank you for assigning this issue to me
